#===============================================================================
#      FILENAME: Makefile
#   DESCRIPTION: ---
#         NOTES: ---
#        AUTHOR: leoxiang, leoxiang727@qq.com
#      REVISION: 2016-04-19 by leoxiang
#===============================================================================

all:
	protoc --go_out=. *.proto

# vim:ts=4:sw=4:ft=make:
