language: go
sudo: false
go:
- 1.5
- 1.6
- tip
before_script:
- go get github.com/mattn/gom
- echo $PATH
- echo $GOPATH
script:
- $HOME/gopath/bin/gom install
- $HOME/gopath/bin/gom test
notifications:
  email:
    recipients:
    - leoxiang727@gmail.com
