language: go
go:
 - 1.5
 - 1.6
sudo: required
install:
- date
- locale
- echo $PATH
- echo $GOPATH
script:
- go test -v ./...
branches:
  only:
  - master
notifications:
  email:
    recipients:
    - leoxiang727@gmail.com
env:
  global:
  - LANG="en_US.UTF-8"
