language: go
sudo: false
go:
 - 1.5
 - 1.6
before_script:
  - go vet ./...
install:
# Add Godeps dependencies to GOPATH and PATH
- export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
- export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
- echo $PATH
- echo $GOPATH
notifications:
  email:
    recipients:
    - leoxiang727@gmail.com
