language: go
sudo: false
go:
- 1.5
- 1.6
- tip
before_script:
- go get github.com/Masterminds/glide
- echo $PATH
- echo $GOPATH
script:
- glide install
- go test -v ./...
notifications:
  email:
    recipients:
    - leoxiang727@gmail.com
